### ISSUE TITLE
Issue in the prepend branch when i try to train the model 

### ISSUE THREAD

**Issue by Nkonstan** [zenggo/affective-decoding-4-empathetic-dialog#1]
I get this when i try to train the model : 

Traceback (most recent call last):
  File "train.py", line 88, in <module>
    trainset, data_loader_train = load_dataset('train', indexer, batch_size)
  File "/content/drive/My Drive/affective-decoding-4-empathetic-dialog/data_loader.py", line 120, in load_dataset
    d['pred_emotion'] = np.load('empdial_dataset/fasttest_pred_emotion_texts.%s.npy' % dataset, allow_pickle=True)
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'empdial_dataset/fasttest_pred_emotion_texts.train.npy'

It misses the "fasttest_pred_emotion_texts.train.npy" ?

**Comment by zerkvii** [comment]
_wget https://dl.fbaipublicfiles.com/parlai/empatheticdialogues/models/fasttext_empathetic_dialogues.mdl_
save this model to save directory and then run fasttext_pred to generate this data
